### PR TITLE
task 11 done

### PR DESCRIPTION
**Pull request by ermondel**
task 11 done
[Demo](https://ermondel.github.io/html5-forms/)
[Source](https://github.com/ermondel/html5-forms)

### CODE REVIEW

**Comment by AleshaOleg** [comment]
Just a few moments there.

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 52 47 pm

When I click outside on button, neighbour button picking

**Comment by AleshaOleg** [comment]
Use `cursor: pointer`
screen shot 2018-01-26 at 9 53 48 pm

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 54 22 pm
Use button

**Comment by ermondel** [comment]
Thank for review
 bug 'click outside' - fixed
 add 'cursor pointer' - done
'Use button' - sorry, but it's already a buttons. But, I have now added a :hover to them.

**Comment by AleshaOleg** [comment]
Well done. Can be merged

**Pull request merged**
