### PR TITLE
Add usides to finalist list

### PR DESCRIPTION
**Pull request by usides**

### CODE REVIEW

**Review by OleksiyRudenko — APPROVED** [review]
Congrats! 🎉
Closed PRs in homeworks confirmed.

**Comment by babayK0** [comment]
My congratulations to you :+1:

**Review by miroslav-kolomiets — APPROVED** [review]

**Review by babayK0 — APPROVED** [review]

**Comment by usides** [comment]
Thanks for this awesome preparatory self-study course!

**Comment by OleksiyRudenko** [comment]
@usides please ping me in teelgram

**Pull request merged**
