### PR TITLE
add intro to summary and task

### PR DESCRIPTION
**Pull request by SerafimPoch**

### CODE REVIEW

**Comment by SerafimPoch** [comment]
What kind of useful links should I add to intro summary? :)

**Comment by AMashoshyna** [comment]
@SerafimPoch this time I would suggest just putting link into Video column, because we did not have much links. As for example, here is one summary from previous course: https://github.com/kottans/JSCourse2017/blob/master/lecture_summary/170921_html.md
But of course there is room for improvement.

**Comment by SerafimPoch** [comment]
I understand. I'll update soon.

**Comment by AMashoshyna** [comment]
@SerafimPoch thanks!

**Pull request merged**
