### PR TITLE
Replacing gitter with telegram links

### PR DESCRIPTION
**Pull request by zonzujiro**
Will close https://github.com/kottans/frontend/issues/124

### CODE REVIEW

**Comment by dmk1111** [comment]
Does it mean that all communication will be moved from gitter to telegram?

**Comment by zonzujiro** [comment]
> Does it mean that all communication will be moved from gitter to telegram?

Yes, kind of. We will not close gitter chat ofc, but telegram will main messenger.

**Comment by zonzujiro** [comment]
> Does it mean that all communication will be moved from gitter to telegram?

Yes, kind of. We will not close gitter chat ofc, but telegram will main messenger.

**Comment by zonzujiro** [comment]
> Does it mean that all communication will be moved from gitter to telegram?

Yes, kind of. We will not close gitter chat ofc, but telegram will main messenger.

**Pull request merged**
