### PR TITLE
update personal info

### PR DESCRIPTION
**Pull request by SerafimPoch**

### CODE REVIEW

**Comment by suchov** [comment]
@SerafimPoch can you pls solve conflicts?

**Comment by SerafimPoch** [comment]
I actually don't know how to solve it

**Comment by suchov** [comment]
Hey @SerafimPoch it looks like you changed frontend to forntend by accident - check the "File changed" tab, thx

**Comment by suchov** [comment]
great @SerafimPoch thx!

**Comment by SerafimPoch** [comment]
thanks

**Pull request merged**
