### PR TITLE
docs: update performance articles

### PR DESCRIPTION
**Pull request by Shramkoweb**
add Unused CSS article

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Thank you for the proposal.
How about moving this new article under Optional materials section?
Reasons:
- not all devs / project use css preprocessors
- not all preprocessors are sass

**Comment by Shramkoweb** [comment]
> Thank you for the proposal.
> How about moving this new article under Optional materials section?
> Reasons:
> 
> * not all devs / project use css preprocessors
> * not all preprocessors are sass

Yes you are right. Create `Styles optimization` title for same articles

**Comment by Shramkoweb** [comment]
@OleksiyRudenko what we waiting ? I need some changes?

**Comment by OleksiyRudenko** [comment]
@Shramkoweb the entire file marked as changed this affects the review process. Putting it back till weekend.

**Pull request closed without merging**
