### PR TITLE
update tasks done by Yevhen Orlov (add Task 11), update schedule.md

### PR DESCRIPTION
**Pull request by yevhenorlov**
Demo: https://yevhenorlov.com/kottans_html5_forms/build/index.html
Repo: https://github.com/yevhenorlov/kottans_html5_forms

I've skipped Task 10 for now, so I updated the file to reflect that.

### CODE REVIEW

**Comment by AleshaOleg** [comment]
Nice job!
One thing needs to be fixed:
screen shot 2018-01-26 at 10 05 26 pm

**Comment by yevhenorlov** [comment]
thanks, fixed!

**Comment by AleshaOleg** [comment]
now, looks good!

**Comment by zonzujiro** [comment]
I think you need another PR for changes in `schedule.md`

**Pull request merged**
