### PR TITLE
add task 01 - html forms

### PR DESCRIPTION
**Pull request by AMashoshyna**

### CODE REVIEW

**Comment by AMashoshyna** [comment]
@cidre no, no external libraries - only regular CSS

**Comment by suchov** [comment]
@AMashoshyna I only suggest to keep going with the task numbers, on this one will be Task_11
what do you think about that?

**Comment by AMashoshyna** [comment]
@suchov sure, I was thinking about it

**Comment by lempiy** [comment]
@cidre You can use [Font Awesome](http://fontawesome.io/) for icons. They shouldn't be precisely equal with original ones.

**Pull request merged**
