### PR TITLE
task 11: HTML5 form done

### PR DESCRIPTION
**Pull request by Xsorter**
Task 11 finished

### CODE REVIEW

**Comment by Xsorter** [comment]
demo: https://xsorter.github.io/kottans_frontend/task_11/

**Comment by AleshaOleg** [comment]
Should be a single line:
screen shot 2018-01-26 at 10 07 12 pm

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 10 07 16 pm
Use button on all trash icons

**Comment by Xsorter** [comment]
Thanks for comments! Fixed

**Pull request merged**
