### PR TITLE
add test task 7 - client-server communication

### PR DESCRIPTION
**Pull request by suchov**

### CODE REVIEW

**Comment by zonzujiro** [comment]
Replaced articles with links to resources related to HTTP/2

**Comment by suchov** [comment]
ok, @zonzujiro @AMashoshyna what do you think about https://www.udacity.com/course/offline-web-applications--ud899 instead

**Comment by suchov** [comment]
The whole list looks like that:
https://www.udacity.com/course/building-high-conversion-web-forms--ud890
https://www.udacity.com/course/make-your-own-2048--ud248 
https://www.udacity.com/course/offline-web-applications--ud899

https://www.udacity.com/course/intro-to-ajax--ud110
https://www.udacity.com/course/intro-to-jquery--ud245
https://www.udacity.com/course/front-end-frameworks--ud894 
https://www.udacity.com/course/javascript-promises--ud898
https://www.udacity.com/course/asynchronous-javascript-requests--ud109
https://www.udacity.com/course/javascript-design-patterns--ud989
https://www.udacity.com/course/javascript-testing--ud549

https://www.udacity.com/course/client-server-communication--ud897

**Comment by zonzujiro** [comment]
@suchov I think it's better than `http` again.

**Comment by suchov** [comment]
@AMashoshyna @zonzujiro changed to Offline Web Applications, approve pls if all looks good

**Comment by AMashoshyna** [comment]
@suchov the course in taught by Jake Archibald and looks really cool, but it's not for beginners (course overview says "Intermediate"). We can try and maybe offer some alternative later.

**Pull request merged**
