### PR TITLE
try-github.io - make only one task mandatory

### PR DESCRIPTION
**Pull request by AMashoshyna**

### CODE REVIEW

**Review by Vitaminvp — APPROVED** [review]
LGTM

**Comment by OleksiyRudenko** [comment]
Oops! Has engaged myself with the same problem. When started working this PR wasn't in place yet.
#302 offers direct link to LearnGitBranching with only 5 out 7 exercises set mandatory.
Sorry for the hustle. We definitely need issues and assignments )
How do we deal with this further?

**Comment by AMashoshyna** [comment]
@OleksiyRudenko Let's keep this one!

**Comment by AMashoshyna** [comment]
Oops, wrong PR. I meant "let's keep your PR". If we can have direct link to "Learn git branching", the it's better I guess

**Review by OleksiyRudenko — APPROVED** [review]
LGTM

**Pull request closed without merging**
