### PR TITLE
task_11 - done

### PR DESCRIPTION
**Pull request by Andrew-Omelchenko**
Form:
[Source](https://github.com/Andrew-Omelchenko/-checkout-page/)
[Demo](https://andrew-omelchenko.github.io/-checkout-page/)

### CODE REVIEW

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 59 43 pm
Wrong padding

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 59 47 pm
remove border

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 59 50 pm
Style this block correctly please

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 10 00 04 pm
Wrong size of icons

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 10 00 09 pm
Use button here

**Comment by Andrew-Omelchenko** [comment]
All items related to your remarks were fixed, I hope)
Thank you for your efforts.
Here are [source](https://github.com/Andrew-Omelchenko/-checkout-page/) and [demo](https://andrew-omelchenko.github.io/-checkout-page/).

**Comment by AleshaOleg** [comment]
Now checkboxes "jumping" when selecting another one.

**Comment by Andrew-Omelchenko** [comment]
"Jumping" checkboxes were fixed. Sorry for delay.

**Comment by Andrew-Omelchenko** [comment]
Links to the source and demo remain the same.

**Comment by AleshaOleg** [comment]
Looks good now:)

**Comment by Andrew-Omelchenko** [comment]
Thank you.

**Pull request merged**
