### PR TITLE
Rearranging order of the offline stage tasks related to git

### PR DESCRIPTION
**Pull request by Dmytraw**
When I was going through offline stage, task 2 - git and github - seemed more basic and provided better introduction than task 0. So i suggest to swap these two tasks.

### CODE REVIEW

**Comment by zonzujiro** [comment]
I have add mentors as reviewers, so let's discuss. Also, probably @Dmytraw is a candidate to a badge? I dunno.

**Comment by OleksiyRudenko** [comment]
Seconding @zonzujiro . We should ask other students that have passed both git related tasks to make sure there is an issue and swapping is an appropriate solution.

**Comment by OleksiyRudenko** [comment]
@Dmytraw You did a big job!

However there are several issues we will face as the course has already launched and many people are somewhere within 3 initial tasks:
* changing task title will break euristic tie between task naming in students' course repos README.md's - _please, consider keeping former titles as intact as only possible_
* changing file names will break links from external repos - _imo filenames may remain intact with no harm to course content, anyway students follow the next task link or `contents.md`; changing descriptive 'collaboration' to ordinal 'intermediate' imo doesn't pay, I'd rather suggest changing `intro` and `advanced` into smth more descriptive_
* if we merge this PR as it is then students who would have just finished Linux CLI will be surprised to see former Git Intro task - _definitely need a Nota Bene for this_

Please, also change order of tasks in `./contents.md` and `./tasks/README.md`.

What do you think re above?

**Comment by Dmytraw** [comment]
@OleksiyRudenko 
I think that this improvement should be introduced in the next iterations of kottans as merging it now will cause a lot of misunderstaning including issues you have described. 

I think task titles should be changed as well because it looks more consistent: git intro (an introduction to a technology) -> git intermediate (some knowledge already acquired, but more practice and techniques to come) -> git advanced (advanced and more specific tools to understand)

`Please, also change order of tasks in ./contents.md and ./tasks/README.md.` will do

**Comment by OleksiyRudenko** [comment]
Added a question re tasks swap to the [General Basics course part survey](https://goo.gl/forms/O80XcZwxhMhGmQKq2)

**Comment by Dmytraw** [comment]
I have updated `contents.md`.

Those numerous commits are my first attempt to rebase :D

**Comment by zonzujiro** [comment]
@Dmytraw first of all, thank you for this PR. It is always great to see activity from our students :)

As was discussed between mentors, there is no necessity in such rearranging of tasks right now.

Maybe we will return to this question after finishing the online part of the course.

**Pull request closed without merging**
