### PR TITLE
change task 11

### PR DESCRIPTION
**Pull request by SerafimPoch**
Task 11 - Finished
Demo: https://serafimpoch.github.io/checkout/
Source: https://github.com/SerafimPoch/kottans_frontend/tree/master/task_11

### CODE REVIEW

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 40 03 pm
Fix paddings, and border for "Add" button.

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 40 09 pm

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 40 20 pm
Use ```<label>``` here.

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 40 29 pm
Use button for trash icon.

**Comment by SerafimPoch** [comment]
Label instead checkbox ?

**Comment by AleshaOleg** [comment]
@SerafimPoch label with checkbox

**Comment by SerafimPoch** [comment]
H, I fix bugs, but in safari it looks like different than in chrome. 
image

**Comment by AleshaOleg** [comment]
@SerafimPoch use `font-size`

**Pull request closed without merging**
