### PR TITLE
Update stage0 finishers

### PR DESCRIPTION
**Pull request by ustymchyk**

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Hi @ustymchyk 
Cannot see any submission on Building Tiny JS World / Pre-OOP among [your PRs](https://github.com/kottans/frontend-2021-homeworks/pulls?q=is%3Apr+author%3Austymchyk+)

Canyou please point me in the right direction? I must have missed something.

**Comment by OleksiyRudenko** [comment]
[Your diary](https://github.com/ustymchyk/kottans-frontend) also doesn't look complete. Can you please comment on this as well?

**Comment by ustymchyk** [comment]
About pre-oop:
I really don`t know how it happened.
I have a branch with my solutions. Maybe I forgot to make a PR.
Should I make a new PR for it?
[my branch](https://github.com/ustymchyk/a-tiny-JS-world/blob/populate-world/index.js)

About diary: 
Do I have to describe my impressions about practice too, or fix a general view?

**Comment by OleksiyRudenko** [comment]
> Hi @OleksiyRudenko!
> 
> About pre-oop:
> I really don`t know how it happened.
> I have a branch with my solutions. Maybe I forgot to make a PR.
> Should I make a new PR for it?
> [my branch](https://github.com/ustymchyk/a-tiny-JS-world/blob/populate-world/index.js)

Yes, please. Otherwise one of eligibility criteria "7 practical tasks/real projects with code review" is not met and number "7" in this your submission is not true.

> About diary:
> Do I have to describe my impressions about practice too, or fix a general view?

Impressions and learnings taken are more important. This helps you reflect on your learnings. Not mandatory though.

Mentors also may refer to the diary if they have qustions as to individual skills and/or completeness of the tasks.

**Comment by OleksiyRudenko** [comment]
Closing this PR as eligibility criteria are not met.

**Pull request closed without merging**
