### PR TITLE
Add an aditional article to rwd task

### PR DESCRIPTION
**Pull request by ORybka**
Please, consider adding this short article.
The part about different types of pixels was pretty difficult to understand but this article helped me a lot.

### CODE REVIEW

**Review by OleksiyRudenko — CHANGES_REQUESTED** [review]
@ORybka Thank you for your submission

However the following action is questionnable
image

Please make sure we do not remove anything important.

**Comment by ORybka** [comment]
@OleksiyRudenko I still have problems with PRs :( I thought in this way I will remove the file only for the review, not for the repo

**Comment by OleksiyRudenko** [comment]
For the record:
This PR resolves #315

**Comment by OleksiyRudenko** [comment]
> @OleksiyRudenko I still have problems with PRs :( I thought in this way I will remove the file only for the review, not for the repo

In homeworks we ask **not to add** (rather than remove) files that are not required for review.
Whatever is commited as deletion gets deleted from the repo.

Just revert your last commit.

**Comment by ORybka** [comment]
@OleksiyRudenko done :)

**Comment by OleksiyRudenko** [comment]
Oh, I see now. This PR also contains changes from #319 

Not a big problem. However it is important to understand why this happened. That happened because you created a branch for this PR not from `master` (or `main`) but from the branch you've created for #319 

image

Although this is not a big issue in this particular case (luckily). But you may want to learn how to fix this type of problems.
Do you want to learn how to fix it?

**Comment by OleksiyRudenko** [comment]
For the record: this PR interferes with #319.

**Comment by ORybka** [comment]
@OleksiyRudenko Yes! Please! I have no idea, how to solve it and I see the mistake

**Review by OleksiyRudenko — APPROVED** [review]
Well done!

**Review by babayK0 — APPROVED** [review]

**Pull request merged**
