### PR TITLE
task 11 done

### PR DESCRIPTION
**Pull request by voveus**
**task 11 done**

- [demo](https://voveus.github.io/checkout_form/)
-  [repo](https://github.com/voveus/checkout_form)

### CODE REVIEW

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 56 09 pm
cursor: pointer

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 56 38 pm
Border jumps there, when pick another radio button

**Comment by AleshaOleg** [comment]
screen shot 2018-01-26 at 9 57 29 pm
Style it correctly please

**Comment by voveus** [comment]
@AleshaOleg thanks a lot! 
check it please

**Comment by AleshaOleg** [comment]
🤔

screen shot 2018-01-27 at 2 17 00 am

**Comment by voveus** [comment]
my bad, entered the wrong link for CSS file

**Comment by AleshaOleg** [comment]
trash icons should be buttons.

**Comment by voveus** [comment]
Fixed, check it please
Appreciate your feedback soooo much!

**Comment by AleshaOleg** [comment]
screen shot 2018-01-30 at 12 31 06 am
Some space at bottom should be removed

**Comment by AleshaOleg** [comment]
screen shot 2018-01-30 at 12 31 52 am 1
Elements should take all free width on this block, as I remember

**Comment by voveus** [comment]
I apologize for a delayed response. 
Fixed, check please

**Pull request merged**
